name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        touch foo-a foo-b foo-c
    - run: |
        find . -name 'foo-*'
        echo "foo=$(find . -name 'foo-*' | tr '\n' ' ')" >> "$GITHUB_OUTPUT"
      id: myfind
    - run: echo ${{ toJson( steps.myfind.outputs.foo ) }}
